##
# A reusable workflow that runs JavaScript tests.
##
name: JavaScript tests

on:
  workflow_call:

jobs:
  # Runs the QUnit test suite.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Sets up Node.js.
  # - Logs debug information about the GitHub Action runner.
  # - Installs npm dependencies.
  # - Run the WordPress QUnit tests.
  # - Ensures version-controlled files are not modified or deleted.
  test-js:
    name: Run QUnit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

      - name: Set up Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Log debug information
        run: |
          npm --version
          node --version
          git --version

      - name: Install npm Dependencies
        run: npm ci

      - name: Run QUnit tests
        run: npm run grunt qunit:compiled

      - name: Ensure version-controlled files are not modified or deleted
        run: git diff --exit-code
