##
# A reusable workflow that reads the .version-support-*.json files and returns values for use in a
# test matrix based on a given WordPress version.
##
name: Determine test matrix values

on:
  workflow_call:
    inputs:
      wp-version:
        description: 'The WordPress version to test . Accepts major and minor versions, "latest", or "nightly". Major releases must not end with ".0".'
        type: string
        default: 'nightly'
      repository:
        description: 'The repository to read support JSON files from.'
        type: string
        default: 'WordPress/wordpress-develop'
    outputs:
      major-wp-version:
        description: "The major WordPress version based on the version provided in wp-version"
        value: ${{ jobs.major-wp-version.outputs.version }}
      php-versions:
        description: "The PHP versions to test for the given wp-version"
        value: ${{ jobs.php-versions.outputs.versions }}
      mysql-versions:
        description: "The MySQL versions to test for the given wp-version"
        value: ${{ jobs.mysql-versions.outputs.versions }}

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  # Determines the major version of WordPress being tested.
  #
  # The data in the JSON files are indexed by major version, so this is used to look up the appropriate support policy.
  #
  # Performs the following steps:
  # - Checks out the repository
  # - Returns the major WordPress version as an output based on the value passed to the wp-version input.
  major-wp-version:
    name: Determine major WordPress version
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      version: ${{ steps.major-wp-version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: ${{ inputs.repository }}
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
          persist-credentials: false

      - name: Determine the major WordPress version
        id: major-wp-version
        run: |
          if [ "${WP_VERSION}" ] && [ "${WP_VERSION}" != "nightly" ] && [ "${WP_VERSION}" != "latest" ] && [ "${WP_VERSION}" != "trunk" ]; then
            echo version="$(echo "${WP_VERSION}" | tr '.' '-' | cut -d '-' -f1-2)" >> "$GITHUB_OUTPUT"
          elif [ "${WP_VERSION}" ] && [ "${WP_VERSION}" != "trunk" ]; then
            echo version="${WP_VERSION}" >> "$GITHUB_OUTPUT"
          else
            echo version="nightly" >> "$GITHUB_OUTPUT"
          fi
        env:
          WP_VERSION: ${{ inputs.wp-version }}

  # Determines the versions of PHP supported for a version of WordPress.
  #
  # Performs the following steps:
  # - Checks out the repository
  # - Returns the versions of PHP supported for the major version of WordPress by parsing the
  #   .version-support-php.json file and returning the values in that version's index.
  php-versions:
    name: Determine PHP versions
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: [ major-wp-version ]
    timeout-minutes: 5
    outputs:
      versions: ${{ steps.php-versions.outputs.versions }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: ${{ inputs.repository }}
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
          persist-credentials: false

      # Look up the major version's specific PHP support policy when a version is provided.
      # Otherwise, use the current PHP support policy.
      - name: Get supported PHP versions
        id: php-versions
        run: |
          if [ "${WP_VERSION}" != "latest" ] && [ "${WP_VERSION}" != "nightly" ]; then
            echo versions="$(jq -r '.["${WP_VERSION}"] | @json' .version-support-php.json)" >> "$GITHUB_OUTPUT" # @TODO finalise
          else
            echo versions="$(jq -r '.[ (keys[-1]) ] | @json' .version-support-php.json)" >> "$GITHUB_OUTPUT"
          fi
        env:
          WP_VERSION: ${{ needs.major-wp-version.outputs.version }}

  # Determines the versions of MySQL supported for a version of WordPress.
  #
  # Performs the following steps:
  # - Checks out the repository
  # - Returns the versions of MySQL supported for the major version of WordPress by parsing the
  #   .version-support-mysql.json file and returning the values in that version's index.
  mysql-versions:
    name: Determine MySQL versions
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: [ major-wp-version ]
    timeout-minutes: 5
    outputs:
      versions: ${{ steps.mysql-versions.outputs.versions }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: ${{ inputs.repository }}
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
          persist-credentials: false

      # Look up the major version's specific MySQL support policy when a version is provided.
      # Otherwise, use the current MySQL support policy.
      - name: Get supported MySQL versions
        id: mysql-versions
        run: |
          if [ "${WP_VERSION}" != "latest" ] && [ "${WP_VERSION}" != "nightly" ]; then
            echo versions="$(jq -r '.["${WP_VERSION}"] | @json' .version-support-mysql.json)" >> "$GITHUB_OUTPUT" # @todo finalise
          else
            echo versions="$(jq -r '.[ (keys[-1]) ] | @json' .version-support-mysql.json)" >> "$GITHUB_OUTPUT"
          fi
        env:
          WP_VERSION: ${{ needs.major-wp-version.outputs.version }}
